@startuml
title General De-Identification Actor Diagram
agent "Data Source" as DocumentSource 
agent "Data Recipient (d)" as DocumentRecipientD
agent "Data Recipient" as DocumentRecipient
agent "De-Identification Service" as DeId
agent "Policy Admin" as admin
agent "De-Identification Policy" as Policy
agent "Data Source (d)" as DocumentSourceD

DocumentSource -> DocumentRecipient : "Send data"
DocumentRecipient .. DeId: "Grouped"
DeId .. DocumentSourceD: "Grouped"
DeId -right-> Policy
admin -down-> Policy
DocumentSourceD -> DocumentRecipientD : "Send data"
@enduml